FROM golang:1.21.6-bookworm

ENV WORK_DIR=$GOPATH/src/github.com/shuricksumy/openvpn-ui
ENV CGO_ENABLED=1
#ENV CGO_CFLAGS="-D_LARGEFILE64_SOURCE"
WORKDIR $WORK_DIR
COPY . .

RUN apt-get update && apt-get install build-essential -y

RUN go install github.com/beego/bee/v2@latest && bee update
RUN go mod tidy && go mod vendor && bee pack bee pack  \
    -exr='^vendor|^data.db|^build|^README.md|^docs|^README_ORIGINAL.md|^screenshots|^pkg|^bin|^dist|^Taskfile|^example|^swagger|^docker-compose|^Dockerfile'
RUN ls -lah $WORK_DIR

FROM scratch
ENV WORK_DIR=/go/src/github.com/shuricksumy/openvpn-ui
COPY --from=0 $WORK_DIR/openvpn-ui.tar.gz /openvpn-ui.tar.gz